### PR TITLE
merge upstream "unknown version" changes

### PR DESCRIPTION
**Pull request by rviscomi**
Captures changes from https://github.com/johnmichel/Library-Detector-for-Chrome/pull/93

null jQuery WPT: https://www.webpagetest.org/custom_metrics.php?test=170407_TK_3Z0J&run=1&cached=0
multi-lib WPT: https://www.webpagetest.org/custom_metrics.php?test=170407_3V_3WKB&run=1&cached=0

### CODE REVIEW

**Comment by rviscomi** [comment]
Just pulling changes from the library detector repo. Merging.

**Comment by rviscomi** [comment]
Updated custom_metrics/ on HA server and pushed changes down to the WPT agents. This should give us unknown version coverage for the 4/15 run.

**Comment by igrigorik** [comment]
👍

**Comment by rviscomi** [comment]
One thing I forgot to do in https://github.com/johnmichel/Library-Detector-for-Chrome/pull/93 is increment the version. HA pulls down the version in `manifest.json` and associates that with the build of `libraries.js`.

Maybe we need a more robust process, like referencing the last commit ID of `libraries.js`.

**Comment by igrigorik** [comment]
Yeah, seems reasonable.

**Pull request merged**
